#!/bin/bash
SCRIPT_FOLDER=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $SCRIPT_FOLDER/../../core_lib/includeBasics.sh

# check, if used tools are installed
# TODO: add tools which are used in this script here in order to check, if they are installed on the system
USED_TOOLS='python3'
MESSAGE=$($LIB_SCRIPT_FOLDER/checkUsedTools.sh "$USED_TOOLS" "check_shflag_tools")
CODE=$?

if [ $CODE -ne 0 ]; then
	echoError "$MESSAGE"
	exit $EXIT_TOOLS_MISSING
fi

# define parameters
DEFINE_string 'fasta' '' 'Fasta file generated by SPAdes assembler.' 'f'
DEFINE_string 'sam' '' 'SAM file containing consensus sequences mapped to fasta file.' 's'
DEFINE_string 'out' '' 'Output fasta file containing detected insertion sequences' 'o'
DEFINE_integer 'maxSize' '8000' '[optional] Maximum length for an insertion. Detected insertions with greater length are discarded.' 'm'
DEFINE_boolean 'ignoreFastaExistence' '1' '[optional] Do not throw an error if fasta file does not exist' 'e'
DEFINE_boolean 'version' 'false' '[optional] prints the version' 'v'
DEFINE_boolean 'debug' 'false' '[optional] prints out debug messages.' ''

# parse parameters
FLAGS "$@" || exit $EXIT_INVALID_ARGUMENTS
eval set -- "${FLAGS_ARGV}"
printParamValues "initial parameters" # print param values, if in debug mode

if [ "$FLAGS_version" -eq 0 ]; then
	MESSAGE="assemblyAnalyzer 1.0"
	echo $MESSAGE
	exit $EXIT_OK
fi

# check if mandatory arguments are there
if [ -z "$FLAGS_out" ]; then
	echoError "Parameter -o must be set. (see --help for details)";
	exit $EXIT_MISSING_ARGUMENTS
fi
if [ -z "$FLAGS_sam" ]; then
	echoError "Parameter -s must be set. (see --help for details)";
	exit $EXIT_MISSING_ARGUMENTS
fi
if [ -z "$FLAGS_fasta" ]; then
	echoError "Parameter -f must be set. (see --help for details)";
	exit $EXIT_MISSING_ARGUMENTS
fi
if [ "$FLAGS_maxSize" -gt 10000000000 ] || [ "$FLAGS_maxSize" -lt 1 ]; then
	echoError "Parameter -m must be between [1, 10000000000]. (see --help for details)";
	exit $EXIT_INVALID_ARGUMENTS
fi

# TODO: add further parameter checks here which refer to input ranges or valid parameters in general here

printParamValues "parameters before actual script starts" # print param values, if in debug mode
##################################################### START with actual SCRIPT ##################################################### 

if [ $FLAGS_ignoreFastaExistence -eq 0 ]; then
    
    if [ ! -f "$FLAGS_fasta" ]; then
        printf "$FLAGS_fasta does not exist. Ignore and exit!\n"
        exit $EXIT_OK
    fi

fi

dirname_out=$(dirname "$FLAGS_out")
if [ ! -d "$dirname_out" ]; then
    mkdir -p "$dirname_out"
fi

command_to_call="python3 /mnt/raidproj/proj/software/watchdog/florian_modules/assemblyAnalyzer/assemblyAnalyzer.py --fasta $FLAGS_fasta --sam $FLAGS_sam --out $FLAGS_out --max_size $FLAGS_maxSize"

MESSAGE=$(eval $command_to_call 2>&1)
RET=$?

# check for error
FAIL=0
TMP_FILE=$(getTmpFile assemblyAnalyzer)
touch "$TMP_FILE"
trap "rm -f \"$TMP_FILE\" 2>&1 > /dev/null" EXIT
printf "$MESSAGE" > "$TMP_FILE"
MESSAGE_ERROR=$($SCRIPT_FOLDER/../../core_lib/errorChecker.sh "$TMP_FILE" "truncated file:fail to open file" 2>&1)
CODE_ERROR=$?
rm -f "$TMP_FILE" 2>&1 > /dev/null

if [ $CODE_ERROR -ne 0 ]; then
	echoError "Error checker found some errors, see found errors below"
	echo -e "$MESSAGE_ERROR"
	exit $EXIT_FAILED
else
	# check exit code
	if [ $FAIL -eq 0 ] && [ $RET -eq 0 ]; then
		# output the original message
		printf "$MESSAGE\n"
		
		exit $EXIT_OK
	else
		FAIL=1
	fi
	if [ $FAIL -eq 1 ]; then
		echoError "Run failed. See error below"
		echoAError "error code: '$RET'"
		 # output the original message
		printf "$MESSAGE\n"
		exit $EXIT_FAILED
	fi
fi


# exit with exit status 0 or exit code should be there earlier
echoError "Reached end of script! Exit should be performed earlier..."
exit $EXIT_REACHED_END_OF_SCRIPT